language: python
python:
  - '3.9'
install:
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt 
script:
  - bash ./scripts/pages.sh
# - python setup.py -q install
deploy:
  # - provider: pypi
  #   user: __token__
  #   password: boxHfbrX0/3uQoUmKsCyZPW+VUE3Aq4A1QI9uEPirja3Enrz73BhvSgzG9vt2Uw81kE1obxXjaXvOyaZNd/2fYMbZ5/M/AEpvjYU3/oxATTniM5IftOq+L7+xjVEmxbZeEyZYg7qKxBVe3p8DG5MP8AD9TQFVk6Z1KuhpciNF611glH8lWTtigDicOUIXE8pLrrZhMIJ3bAd0rG+yCeqA1IwfwqgRjUZde+w+/15DbPEw9P6nxF0td1lyIljlzZyByAeRi46/ZQ5GmqUCUVcPHcdw4BsGXcx8sj8+2bbh0GW5b6hG6bA4mrh3XHUupRFP+yLy9s+PLOC6fSerXlfkqqoxUz++3RX9kLVyoE+vFKHxdA4jiT6mrdriD9C7lo79H2ni9LgM9NeGAVMXDBc5Vw2o+LCmj6B2JxtA5AYQyYtMSGLnDoT2NQXfNBZHydoMhM+GvcQUu+CPnPrrid2aa7Zv8XRSdxKJetETHLsSDCB2ZE8YUgnyvB4+IbrO3hbJ/4RUyekuwyrQKFYeM2fSl0uHGVVsSMX/X+3Kg6w+riSOss4mJTBPN9UqRXDByJgC6l3/upRqkKQwJAwms1L3iM4pgPbL1ztbwyHXSvciftQDHtx/adfRtiEB7GP4ThMbQewzfC/cgagVeA8ixoRszRvYgE/s9/D/0oxvC59As0=
  #   on:
  #     python: 3.9
  #     # tags: true
  #     branch: master
  #   edge: true
  #   cleanup: true
  - provider: pages:git
    token:
      secure: Eyc22GvaunHjwwrIkyDTjrZLovhnbdnREk+Fu9UihxQQXgmnXN5UG/lDna0EstJdA/bz/XXLjP1XPAQhG8VQBgt7Cb06YPI7R51Rj6RCC/Cf0kmz+fVEA9NFpUU5nUnBd9H6IjJV1wMBAFSrENo+WZ0Djzr5mWDMs0vouvhidVpxjff0CmEXjtLDjqy4DUu7mrYkL1qOHLvy/l9IaAmmsrGHWZN4XUnJhtzWEeVaRUuKT40Jh6YwV47CNJ7RQOa58apU/WlvHTFpuvxi96RGeM25FeFfhvhfSF20zM9SuQdkvZ28MqTJmQIxXf12fFlrFtwQX0MVpwgOs2Jf8vYLdOt2YueZa4wYqR1GJ7HFxdE/TE026VtrXy4qO9c4Ad3TdIeE+Ypaf+HVizFTUPuPHZ65QSoLe97wRAdMa9hdrGQxhZjDAJfNCS8VVtr07k55xdLh79rVKu2uTBdZ2z7/EKvXzOTiI/G8Gk35OsCSYiIkRo1pXDYdV5mOIIx2LWqZe1etGK/RfigFnWu3PEQnz9KUduYfFXqpgC4JEOInk+jEogG9ihDZYjS+5LlH/fq2uEWIgIMr9QGGX1ZaGFnqx35fHeNuqlepquQuix507TR8SXGVKVPMy/XQh3FH2SvzHjOsw2vokzYGnW+GI0Qy9nEsMfiXmQsWvQ9dfItPBGY=
      local_dir: ./docs/build/
      on:
      python: 3.9
      # tags: true
      branch: master
    edge: true
    cleanup: false
# addons:
#   apt:
#     update: true
#     sources:
#     - 
