name: github pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: local0state/trojanzoo:sphinx
      # ports: 80
    # strategy:
    #   matrix:
    #     # os: [ubuntu-latest, macos-latest, windows-latest]
    #     python-version: [3.9.1]
    #     # exclude:
    #     #   - os: macos-latest
    #     #     python-version: 3.9.1
    #     #   - os: windows-latest
    #     #     python-version: 3.9.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r ./docs/requirements.txt
      - name: Compile Sphinx Docs
        run: |
          cd ./docs/
          make html-stable
          touch /docs/build/html/.nojekyll
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v2
        with:
          pages_threshold: major_outage
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./docs/build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
