name: release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [created]

jobs:
  pypi:
    runs-on: ubuntu-latest
    container:
      image: local0state/trojanzoo:sphinx
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel pep517 twine
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m pep517.build .
          twine upload dist/
      # - name: Repository Dispatch
      #   if: ${{ success() }}
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     repository: ${{ github.repository }}
      #     event-type: pypi_success
      #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
  docker:
    needs: pypi
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./cpu.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trojanzoo:cpu
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
