name: release

on:
  release:
    types: [created]

jobs:
  pypi:
    runs-on: ubuntu-latest
    container:
      image: local0state/base:cpu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          pip install --no-cache-dir setuptools wheel pep517 twine
          python -m pep517.build .
          twine upload dist/*
  # conda:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: local0state/base:cpu-conda
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Build and publish
  #       env:
  #         TWINE_USERNAME: __token__
  #         TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
  #         ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
  #       run: |
  #         conda install -y anaconda-client conda-build
  #         conda build .
  cpu:
    name: docker-cpu
    needs: pypi
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/${{ github.job }}.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.job }}
  gpu:
    name: docker-gpu
    needs: pypi
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/${{ github.job }}.dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.job }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest